[package]
name = "kcp-bindings"
version = "1.0.0"
edition = "2021"
build = "build.rs"

[dependencies]
tokio = { version = "1.41.0", features = ["full"], optional = true }
anyhow = "1.0.91"

[features]
hexfellow = ["dep:tokio"]

[build-dependencies]
cc = "1.1"
bindgen = "0.71.0"
